### PR TITLE
Refine ProgramState mat id

### PR DESCRIPTION
**Pull request by halx99**

### CODE REVIEW

**Comment by halx99** [comment]
> > We also can provide setUniformID manually for user to avoid calculate uniformID with uniform buffer automatically, what do you think about?
> 
> That would be a good idea, in case the performance is affected by the XXH32 calculation.

@rh101 Please help review the latest commit, I implement the idea

**Comment by rh101** [comment]
The latest commit with the `setUniformID` seems fine.

**Comment by halx99** [comment]
Thanks

**Comment by halx99** [comment]
well, i have test again, with seems with your implementation, cocos-re full fbo test fps is 36fps

**Comment by halx99** [comment]
so, currently, i think your implementation is best

**Comment by rh101** [comment]
I don't know much about rendering pipelines and such, so please correct me if I'm wrong, but isn't the sprite texture stored in the FBO?  If that is the case, then the XXH32 processing time would greatly affected by the texture size, and that would explain the low FPS.

**Comment by halx99** [comment]
Because every render node call setUniform per frame

**Comment by rh101** [comment]
I understand, so it would be quite intensive if the hashing algorithm is running every frame.

**Comment by halx99** [comment]
> I understand, so it would be quite intensive if the hashing algorithm is running every frame.

Yes, so I modify the code, let's user to call updateUniformID when their shader have unstable uniform variables needs to set

**Comment by halx99** [comment]
@rh101 If you have no other qusetion, I will merge this pr

**Comment by rh101** [comment]
The changes look good.  Thank you for working on all of this.

**Comment by halx99** [comment]
Thanks, merged

**Pull request merged**
